import yaml from 'js-yaml';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import type { ScannedModule } from '../types.js';
import { annotationsToDict } from '../serializers.js';
import type { WriteResult, Verifier } from './types.js';
import { createWriteResult } from './types.js';
import { WriteError } from './errors.js';
import { YAMLVerifier, runVerifierChain } from './verifiers.js';

export class YAMLWriter {
  write(
    modules: ScannedModule[],
    outputDir: string,
    options?: { dryRun?: boolean; verify?: boolean; verifiers?: Verifier[] },
  ): WriteResult[] {
    const dryRun = options?.dryRun ?? false;
    const shouldVerify = options?.verify ?? false;
    const verifiers = options?.verifiers ?? [];

    if (modules.length === 0) {
      return [];
    }

    const outputPath = resolve(outputDir);

    if (!dryRun) {
      mkdirSync(outputPath, { recursive: true });
    }

    const results: WriteResult[] = [];
    const timestamp = new Date().toISOString();

    for (const module of modules) {
      const bindingData = this._buildBinding(module);

      if (dryRun) {
        results.push(createWriteResult(module.moduleId, null));
        continue;
      }

      let safeId = module.moduleId.replace(/[^a-zA-Z0-9._-]/g, '_');
      safeId = safeId.replace(/\.{2,}/g, '_');
      const filename = `${safeId}.binding.yaml`;
      const filePath = resolve(join(outputPath, filename));

      // Path traversal protection
      if (!filePath.startsWith(outputPath)) {
        console.warn('Skipping file outside output directory: %s', filePath);
        continue;
      }

      if (existsSync(filePath)) {
        console.warn('Overwriting existing file: %s', filePath);
      }

      const header =
        `# Auto-generated by apcore-toolkit scanner\n` +
        `# Generated: ${timestamp}\n` +
        `# Do not edit manually unless you intend to customize schemas.\n\n`;

      const yamlContent = yaml.dump(bindingData, {
        flowLevel: -1,
        sortKeys: false,
      });

      try {
        writeFileSync(filePath, header + yamlContent, 'utf-8');
      } catch (err) {
        throw new WriteError(filePath, err as Error);
      }

      let result = createWriteResult(module.moduleId, filePath);
      if (shouldVerify) {
        const builtinResult = new YAMLVerifier().verify(filePath, module.moduleId);
        if (!builtinResult.ok) {
          result = createWriteResult(module.moduleId, filePath, false, builtinResult.error ?? null);
        }
      }
      if (result.verified && verifiers.length > 0) {
        const vResult = runVerifierChain(verifiers, filePath, module.moduleId);
        if (!vResult.ok) {
          result = createWriteResult(module.moduleId, filePath, false, vResult.error ?? null);
        }
      }
      results.push(result);
    }

    return results;
  }

  private _buildBinding(module: ScannedModule): Record<string, unknown> {
    return {
      bindings: [
        {
          module_id: module.moduleId,
          target: module.target,
          description: module.description,
          documentation: module.documentation,
          tags: [...module.tags],
          version: module.version,
          annotations: annotationsToDict(module.annotations),
          examples: module.examples.length > 0
            ? module.examples.map((e) => ({ ...e }))
            : [],
          metadata: structuredClone(module.metadata),
          input_schema: structuredClone(module.inputSchema),
          output_schema: structuredClone(module.outputSchema),
        },
      ],
    };
  }
}
