import yaml from 'js-yaml';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import type { ScannedModule } from '../types.js';
import { annotationsToDict } from '../serializers.js';

export class YAMLWriter {
  write(
    modules: ScannedModule[],
    outputDir: string,
    options?: { dryRun?: boolean },
  ): Record<string, unknown>[] {
    const dryRun = options?.dryRun ?? false;

    if (modules.length === 0) {
      return [];
    }

    const outputPath = resolve(outputDir);

    if (!dryRun) {
      mkdirSync(outputPath, { recursive: true });
    }

    const results: Record<string, unknown>[] = [];
    const timestamp = new Date().toISOString();

    for (const module of modules) {
      const bindingData = this._buildBinding(module);
      results.push(bindingData);

      if (!dryRun) {
        let safeId = module.moduleId.replace(/[^a-zA-Z0-9._-]/g, '_');
        safeId = safeId.replace(/\.{2,}/g, '_');
        const filename = `${safeId}.binding.yaml`;
        const filePath = resolve(join(outputPath, filename));

        // Path traversal protection
        if (!filePath.startsWith(outputPath)) {
          console.warn('Skipping file outside output directory: %s', filePath);
          continue;
        }

        if (existsSync(filePath)) {
          console.warn('Overwriting existing file: %s', filePath);
        }

        const header =
          `# Auto-generated by apcore-toolkit scanner\n` +
          `# Generated: ${timestamp}\n` +
          `# Do not edit manually unless you intend to customize schemas.\n\n`;

        const yamlContent = yaml.dump(bindingData, {
          flowLevel: -1,
          sortKeys: false,
        });

        writeFileSync(filePath, header + yamlContent, 'utf-8');
      }
    }

    return results;
  }

  private _buildBinding(module: ScannedModule): Record<string, unknown> {
    return {
      bindings: [
        {
          module_id: module.moduleId,
          target: module.target,
          description: module.description,
          documentation: module.documentation,
          tags: [...module.tags],
          version: module.version,
          annotations: annotationsToDict(module.annotations),
          examples: module.examples.length > 0
            ? module.examples.map((e) => ({ ...e }))
            : [],
          metadata: { ...module.metadata },
          input_schema: { ...module.inputSchema },
          output_schema: { ...module.outputSchema },
        },
      ],
    };
  }
}
